server {
    listen 80;
    server_name _;

    location /api/catalog/ {
        proxy_pass http://catalog-api:8000/;
    }

    location /api/reservations/ {
        proxy_pass http://reservation-api:8000/;
    }

    location = /health {
        default_type application/json;
        return 200 '{"status":"healthy","service":"frontend"}';
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}